"""Inspect an AADR .anno file and write a markdown report.

Usage (from pipeline/):
    uv run python -m aadr.inspect_anno [--out ../research/sources/aadr-v66.p1-inspection.md]

The report is descriptive only; it changes nothing. Numbers in it are produced
by this script from the checksummed raw file, so re-running it reproduces them.
"""

from __future__ import annotations

import argparse
from collections import Counter
from pathlib import Path

import polars as pl

from aadr.columns import COLUMNS, MISSING, read_anno
from aadr.dates import bp_to_year, date_kind, parse_full_date
from aadr.download import RAW_DIR, md5sum
from aadr.manifest import PRIMARY_ANNO, RELEASE

REPO = Path(__file__).resolve().parents[2]
V1_START, V1_END = -49999, 1500  # 50,000 BCE .. 1500 CE (astronomical)


def blank(col: str) -> pl.Expr:
    return pl.col(col).is_null() | pl.col(col).str.strip_chars().is_in(MISSING)


def md_table(df: pl.DataFrame) -> str:
    cols = df.columns
    lines = ["| " + " | ".join(cols) + " |", "|" + "---|" * len(cols)]
    for row in df.iter_rows():
        lines.append("| " + " | ".join("" if v is None else str(v).replace("|", "\\|") for v in row) + " |")
    return "\n".join(lines)


def decimals(s: str | None) -> int:
    if s is None or s.strip() in MISSING:
        return -1
    s = s.strip()
    return len(s.split(".")[1]) if "." in s else 0


def main() -> None:
    ap = argparse.ArgumentParser()
    ap.add_argument("--anno", type=Path, default=RAW_DIR / PRIMARY_ANNO)
    ap.add_argument("--out", type=Path, default=REPO / "research" / "sources" / f"aadr-{RELEASE}-inspection.md")
    args = ap.parse_args()

    df = read_anno(args.anno)
    out: list[str] = []
    w = out.append

    w(f"# AADR {RELEASE} — inspection report (`{args.anno.name}`)\n")
    w("Generated by `pipeline/aadr/inspect_anno.py`; do not edit by hand. ")
    w(f"File md5: `{md5sum(args.anno)}`.\n")

    df = df.with_columns(
        pl.col("date_mean_bp").cast(pl.Int64, strict=False).alias("_bp"),
        pl.col("date_sd_bp").cast(pl.Int64, strict=False).alias("_sd"),
        pl.col("latitude").cast(pl.Float64, strict=False).alias("_lat"),
        pl.col("longitude").cast(pl.Float64, strict=False).alias("_lon"),
        pl.col("date_method").map_elements(date_kind, return_dtype=pl.String).alias("_kind"),
    )
    n = df.height
    present = df.filter(pl.col("_kind") == "present_day")
    anc = df.filter(pl.col("_kind") != "present_day")
    w("## Row counts\n")
    w(f"- Rows (genetic IDs): **{n}**; columns: {len(COLUMNS)}")
    w(f"- Present-day rows (date method `Modern`): {present.height}")
    w(f"- Non-present-day rows: {anc.height}; unique `individual_id`: **{anc['individual_id'].n_unique()}**")
    refs = df.filter(pl.col("data_suffixes").str.contains("REF"))
    w(f"- Reference rows (suffix REF: ancestral/chimp/gorilla/human reference): {refs.height}")
    w(f"- Unparseable `date_mean_bp`: {df['_bp'].null_count()}; negative BP (post-1950): {df.filter(pl.col('_bp') < 0).height}\n")

    # Duplicates
    dup = anc.group_by("individual_id").agg(
        pl.len().alias("n"),
        pl.col("_bp").n_unique().alias("n_dates"),
        pl.col("_lat").n_unique().alias("n_lat"),
        pl.col("group_id").n_unique().alias("n_groups"),
    )
    multi = dup.filter(pl.col("n") > 1)
    w("## Multiple rows per individual\n")
    w(
        f"{multi.height} ancient individuals have more than one row (max {dup['n'].max()}); these are different data "
        "versions of the same person (e.g. capture vs shotgun, or re-publication), not different people. "
        f"Among them, {multi.filter(pl.col('n_dates') > 1).height} have differing date means, "
        f"{multi.filter(pl.col('n_lat') > 1).height} differing latitudes, and "
        f"{multi.filter(pl.col('n_groups') > 1).height} differing Group IDs across rows. "
        "Normalization must pick one representative row per individual (AADR's own advice: the row with the "
        "most SNPs hit) and record the alternatives.\n"
    )
    ex = (
        anc.join(multi.filter(pl.col("n_groups") > 1).select("individual_id"), on="individual_id")
        .select("individual_id", "genetic_id", "group_id", "date_mean_bp")
        .sort("individual_id")
        .head(8)
    )
    w("Example individuals whose rows carry different Group IDs:\n")
    w(md_table(ex) + "\n")

    # Dates
    w("## Dates\n")
    kinds = anc.group_by("_kind").len().sort("len", descending=True)
    w("Coarse dating method (derived from the free-text `Method for Determining Date`):\n")
    w(md_table(kinds.rename({"_kind": "kind", "len": "rows"})) + "\n")
    w(f"`Method for Determining Date` has {anc['date_method'].n_unique()} distinct free-text values. "
      f"Rows whose method text contains 'WARNING' or 'CAUTION': "
      f"{anc.filter(pl.col('date_method').str.to_uppercase().str.contains('WARNING|CAUTION')).height}.\n")
    parsed = [parse_full_date(s) for s in anc["full_date"].to_list()]
    ok = sum(p is not None for p in parsed)
    w(f"`Full Date` parsed by `aadr/dates.py`: {ok}/{anc.height} rows ({100 * ok / anc.height:.2f}%). "
      f"Calibrated-radiocarbon intervals: {sum(1 for p in parsed if p and p.calibrated)}; "
      f"with conventional 14C age and lab code: {sum(1 for p in parsed if p and p.lab_code)}; "
      f"open-ended ('>'): {sum(1 for p in parsed if p and p.open_ended)}.\n")
    unparsed = [s for s, p in zip(anc["full_date"].to_list(), parsed) if p is None]
    if unparsed:
        w("Unparsed examples: " + "; ".join(f"`{u}`" for u in unparsed[:10]) + "\n")
    # Consistency: parsed midpoint vs date_mean_bp
    diffs = []
    for p, bp in zip(parsed, anc["_bp"].to_list()):
        if p and bp is not None:
            mid = (p.start + p.end) / 2
            diffs.append(abs(mid - bp_to_year(bp)))
    big = sum(1 for d in diffs if d > 500)
    w(f"Midpoint of parsed `Full Date` vs `date_mean_bp` differs by >500 years in {big} rows "
      "(expected for asymmetric calibrated intervals only at small scale; larger gaps are curation issues to check).\n")
    sd = anc["_sd"]
    w(f"Date SD (years): median {sd.median()}, 90th pct {sd.quantile(0.9)}, max {sd.max()}; "
      f"rows with SD = 0: {anc.filter(pl.col('_sd') == 0).height}.\n")

    w("### Ancient rows by age (date_mean_bp)\n")
    bins = [0, 500, 1000, 2000, 3000, 4000, 5000, 6000, 8000, 10000, 12000, 15000, 20000, 30000, 40000, 52000, 10**7]
    rows = []
    for lo, hi in zip(bins[:-1], bins[1:]):
        s = anc.filter((pl.col("_bp") >= lo) & (pl.col("_bp") < hi))
        rows.append((f"{lo}–{hi if hi < 10**7 else '…'} BP", s.height, s["individual_id"].n_unique()))
    w(md_table(pl.DataFrame(rows, schema=["age band", "rows", "individuals"], orient="row")) + "\n")
    in_v1 = anc.filter(
        (pl.col("_bp").map_elements(bp_to_year, return_dtype=pl.Int64) >= V1_START)
        & (pl.col("_bp").map_elements(bp_to_year, return_dtype=pl.Int64) <= V1_END)
    )
    w(f"Ancient individuals with mean date inside V1 (50,000 BCE – 1500 CE): **{in_v1['individual_id'].n_unique()}** "
      f"({in_v1.height} rows). Older than 50,000 BCE (archaic/early, outside V1 window): "
      f"{anc.filter(pl.col('_bp') > 51950)['individual_id'].n_unique()}.\n")

    # Coordinates
    w("## Coordinates\n")
    nocoord = anc.filter(pl.col("_lat").is_null() | pl.col("_lon").is_null())
    w(f"Ancient rows with missing latitude/longitude: {nocoord.height}. "
      f"Out-of-range values: {anc.filter((pl.col('_lat').abs() > 90) | (pl.col('_lon').abs() > 180)).height}. "
      f"Exactly (0,0): {anc.filter((pl.col('_lat') == 0) & (pl.col('_lon') == 0)).height}.\n")
    dec = Counter(decimals(s) for s in anc["latitude"].to_list())
    w("Latitude decimal places as written (a rough proxy for coordinate precision; AADR has no explicit precision field):\n")
    w(md_table(pl.DataFrame(sorted(dec.items()), schema=["decimals (-1 = missing)", "rows"], orient="row")) + "\n")
    sites = anc.group_by("_lat", "_lon").agg(pl.col("individual_id").n_unique().alias("n")).sort("n", descending=True)
    w(f"Distinct coordinate pairs (ancient): {sites.height}; largest single-coordinate cluster: {sites['n'].max()} individuals. "
      "Many individuals share one site coordinate, so points must be jittered or aggregated for display, "
      "and coordinates should be treated as site-level, not burial-level.\n")

    # Labels
    w("## Group labels (`Group ID`)\n")
    g = anc["group_id"]
    w(f"Distinct Group IDs among ancient rows: {g.n_unique()}. Groups with exactly one individual: "
      f"{anc.group_by('group_id').agg(pl.col('individual_id').n_unique().alias('n')).filter(pl.col('n') == 1).height}.\n")
    w(f"Labels carrying an outlier marker (`-o`, `.o`, `_o`, optionally followed by digits or a direction such as `-oEastAsia`): "
      f"{anc.filter(pl.col('group_id').str.contains(r'[-.]o(\d|[A-Z]|$|[_.-])|_o(\d|$|[_.-])')).height} rows. "
      f"Labels containing `_rel`/`rel.`/relative markers: {anc.filter(pl.col('group_id').str.contains('rel')).height} rows. "
      f"Labels starting with `Ignore`: {anc.filter(pl.col('group_id').str.starts_with('Ignore')).height}.\n")
    toks = anc["group_id"].str.split("_").explode().value_counts().sort("count", descending=True).head(40)
    w("Most frequent `_`-separated tokens (shows the Country_Site_Period_Culture convention):\n")
    w(md_table(toks.rename({"group_id": "token"})) + "\n")

    # Political entity
    w("## Political entity (modern country)\n")
    pe = anc.group_by("political_entity").agg(pl.col("individual_id").n_unique().alias("individuals")).sort(
        "individuals", descending=True
    )
    w(f"{pe.height} distinct values. Top 25:\n")
    w(md_table(pe.head(25)) + "\n")

    # Quality
    w("## Quality flags\n")
    w(md_table(anc.group_by("assessment").len().sort("len", descending=True).rename({"len": "rows"})) + "\n")
    w(md_table(anc.group_by("molecular_sex").len().sort("len", descending=True).rename({"len": "rows"})) + "\n")
    snp = anc["snps_1240k"].cast(pl.Int64, strict=False)
    w(f"SNPs hit on 1240k targets: median {snp.median()}, rows with < 20,000: {(snp < 20000).sum()}, "
      f"< 5,000: {(snp < 5000).sum()}.\n")

    # Missingness
    w("## Missing-value rates (ancient rows; '..', '', 'n/a', 'NA' counted as missing)\n")
    miss = []
    for short, _ in COLUMNS:
        m = anc.select(blank(short).sum()).item()
        miss.append((short, m, f"{100 * m / anc.height:.1f}%"))
    w(md_table(pl.DataFrame(miss, schema=["column", "missing", "rate"], orient="row")) + "\n")

    # Publications
    w("## Publications\n")
    w(f"Distinct `publication` keys: {anc['publication'].n_unique()}; rows without a DOI: "
      f"{anc.filter(blank('doi')).height}.\n")

    args.out.parent.mkdir(parents=True, exist_ok=True)
    args.out.write_text("\n".join(out))
    print(f"wrote {args.out}")


if __name__ == "__main__":
    main()
