"""Write research/notes/data-report.md: counts by period, region and population; missing-data rates."""

from __future__ import annotations

import json
from pathlib import Path

import polars as pl

from aadr.manifest import RELEASE

REPO = Path(__file__).resolve().parents[1]
PROC = REPO / "data" / "processed"

# Coarse world regions by lon/lat box: a reporting convenience only (not used in the app).
REGIONS = [
    ("North Africa", -18, 18, 34, 37.5), ("Near East & Caucasus", 25, 12, 63, 45), ("Europe", -25, 34, 45, 72),
    ("Sub-Saharan Africa", -20, -36, 52, 18), ("Central Asia & steppe", 45, 35, 90, 60), ("Siberia", 60, 50, 180, 78),
    ("South Asia", 60, 5, 92, 37), ("East Asia", 92, 18, 150, 55), ("Southeast Asia", 92, -11, 130, 22),
    ("Oceania", 110, -50, 180, -11), ("Pacific (east of 180)", -180, -50, -120, 30), ("North America", -170, 15, -50, 75),
    ("Central & South America & Caribbean", -120, -56, -30, 15),
]


def region_of(lat, lon):
    if lat is None or lon is None:
        return "unknown"
    for name, x0, y0, x1, y1 in REGIONS:
        if x0 <= lon <= x1 and y0 <= lat <= y1:
            return name
    return "other"


def md(df: pl.DataFrame) -> str:
    out = ["| " + " | ".join(df.columns) + " |", "|" + "---|" * len(df.columns)]
    out += ["| " + " | ".join(str(v) for v in r) + " |" for r in df.iter_rows()]
    return "\n".join(out)


def main() -> None:
    ind = pl.read_parquet(PROC / f"aadr_{RELEASE}_individuals.parquet")
    ind = ind.with_columns(((pl.col("start") + pl.col("end")) / 2).alias("mid"),
                           pl.struct("lat", "lon").map_elements(lambda s: region_of(s["lat"], s["lon"]), return_dtype=pl.String).alias("region"))
    bins = [(-60000, -15000, "before 15,000 BCE"), (-15000, -6000, "15,000–6,000 BCE"), (-6000, -3000, "6,000–3,000 BCE"),
            (-3000, 0, "3,000–1 BCE"), (0, 1500, "1–1500 CE"), (1500, 2100, "after 1500 CE")]
    ind = ind.with_columns(pl.col("mid").map_elements(lambda m: next((b[2] for b in bins if b[0] <= m < b[1]), "older"), return_dtype=pl.String).alias("period"))
    tab = ind.pivot(on="period", index="region", values="individual_id", aggregate_function="len").fill_null(0)
    cols = ["region"] + [b[2] for b in bins if b[2] in tab.columns]
    tab = tab.select(cols).sort("region")
    mem = pl.read_parquet(PROC / "membership.parquet")
    pc = mem.group_by("population_id").len().sort("len", descending=True)
    lines = [
        "# Data report", "", f"Generated by `pipeline/data_report.py` from AADR {RELEASE} (ancient individuals, one row per Individual ID). Regions are coarse lon/lat boxes for reporting only.", "",
        f"Total ancient individuals: {ind.height}. With coordinates: {ind.filter(pl.col('lat').is_not_null()).height}. Assigned to a curated population: {mem['individual_id'].n_unique()}.", "",
        "## Individuals by region and period (by midpoint of date range)", "", md(tab), "",
        "## Members per population", "", md(pc.rename({"population_id": "population", "len": "members"})), "",
        "## Missing-data and quality rates", "",
        f"- Coordinates missing: {ind.filter(pl.col('lat').is_null()).height}",
        f"- Coordinate precision: " + ", ".join(f"{a} {b}" for a, b in ind.group_by('precision').len().sort('precision').iter_rows()),
        f"- Date kind: " + ", ".join(f"{a} {b}" for a, b in ind.group_by('date_kind').len().sort('len', descending=True).iter_rows()),
        f"- Date conflicts (text vs numeric): {ind.filter(pl.col('date_conflict').is_not_null()).height}",
        f"- Quality CRITICAL (excluded from memberships by default): {ind.filter(~pl.col('quality_usable')).height}",
        f"- Overrides applied: {sum(len(x) for x in ind['override_ids'])}",
        f"- mtDNA haplogroup missing: {ind.filter(pl.col('mt_hg').is_null()).height}; Y haplogroup missing (incl. females): {ind.filter(pl.col('y_hg').is_null()).height}",
    ]
    (REPO / "research" / "notes" / "data-report.md").write_text("\n".join(lines) + "\n")
    print("wrote research/notes/data-report.md")


if __name__ == "__main__":
    main()
