"""Assign AADR individuals to curated populations using their membership rules.

Usage (from pipeline/):
    uv run python -m populations.membership

Reads:  data/processed/aadr_<release>_individuals.parquet, data/curated/populations.json
Writes: data/processed/membership.parquet  (individual_id, population_id)
        research/notes/membership-report.md (per-population matches, for human review)

Rule semantics (DATA_MODEL.md §3): an individual belongs to a population if its
verbatim group label matches ANY include rule (and that rule's optional date and
bbox constraints), does not match the population's exclude regex or the global
default exclude regex, is not explicitly excluded, and is quality-usable (not
CRITICAL) unless the population sets include_questionable.
"""

from __future__ import annotations

import json
import re
from pathlib import Path

import polars as pl

from aadr.manifest import RELEASE

REPO = Path(__file__).resolve().parents[2]
CURATED = REPO / "data" / "curated"
PROCESSED = REPO / "data" / "processed"


def load_populations() -> tuple[list[dict], str]:
    d = json.loads((CURATED / "populations.json").read_text())
    return d["populations"], d["default_exclude_group_label_regex"]


def overlaps(s: int, e: int, w: dict | None) -> bool:
    return w is None or (s <= w["end"] and e >= w["start"])


def in_bbox(lat, lon, bbox) -> bool:
    if bbox is None:
        return True
    if lat is None or lon is None:
        return False
    return bbox[0] <= lon <= bbox[2] and bbox[1] <= lat <= bbox[3]


def assign(ind: pl.DataFrame, pops: list[dict], default_exclude: str) -> pl.DataFrame:
    dflt = re.compile(default_exclude)
    rows = ind.select("individual_id", "group_label", "start", "end", "lat", "lon", "quality_usable").to_dicts()
    out = []
    for p in pops:
        m = p["membership"]
        if p.get("inferred_only"):
            continue
        incl = [(re.compile(r["group_label_regex"]), r.get("date_within"), r.get("bbox")) for r in m["include"]]
        excl = re.compile(m["exclude_group_label_regex"]) if m.get("exclude_group_label_regex") else None
        ex_ids = set(m.get("exclude_individual_ids", []))
        add_ids = set(m.get("include_individual_ids", []))
        for r in rows:
            lbl = r["group_label"]
            hit = r["individual_id"] in add_ids
            if not hit:
                for rx, w, bb in incl:
                    if rx.search(lbl) and overlaps(r["start"], r["end"], w) and in_bbox(r["lat"], r["lon"], bb):
                        hit = True
                        break
                if hit and ((dflt.search(lbl) and not p.get("ignore_default_exclude")) or (excl and excl.search(lbl))):
                    hit = False
            if hit and r["individual_id"] in ex_ids:
                hit = False
            if hit and not r["quality_usable"] and not m.get("include_questionable"):
                hit = False
            if hit:
                out.append({"individual_id": r["individual_id"], "population_id": p["id"]})
    return pl.DataFrame(out, schema={"individual_id": pl.String, "population_id": pl.String})


def display_range(starts: pl.Series, ends: pl.Series) -> tuple[int, int]:
    """Population display range from member date ranges.

    Very broad contextual ranges on a few members (e.g. "800 BCE - 600 CE") would
    otherwise stretch a population's lifespan band far beyond where most members
    lie. With 20+ members we use the 5th percentile of starts and the 95th
    percentile of ends; with fewer, the full span.
    """
    if starts.len() < 20:
        return int(starts.min()), int(ends.max())
    return int(starts.quantile(0.05, "lower")), int(ends.quantile(0.95, "higher"))


def report(ind: pl.DataFrame, mem: pl.DataFrame, pops: list[dict]) -> str:
    j = mem.join(ind, on="individual_id")
    lines = [
        "# Population membership report",
        "",
        f"Generated by `pipeline/populations/membership.py` from AADR {RELEASE}. For review: check that each population's matched labels are the intended ones.",
        "",
        "| population | members | sites | display range (P5 start … P95 end) | full span of member ranges | matched AADR labels (count) |",
        "|---|---|---|---|---|---|",
    ]
    for p in pops:
        if p.get("inferred_only"):
            lines.append(f"| `{p['id']}` | inferred only | – | {p['time_range']['start']} … {p['time_range']['end']} (display window) | – | – |")
            continue
        s = j.filter(pl.col("population_id") == p["id"])
        if s.height == 0:
            lines.append(f"| `{p['id']}` | **0** | 0 | – | – | **no matches** |")
            continue
        labels = s.group_by("group_label").len().sort("len", descending=True)
        lab = "; ".join(f"{a} ({b})" for a, b in labels.iter_rows())
        sites = s.select(pl.struct("lat", "lon").n_unique()).item()
        lo, hi = display_range(s["start"], s["end"])
        lines.append(f"| `{p['id']}` | {s.height} | {sites} | {lo} … {hi} | {s['start'].min()} … {s['end'].max()} | {lab} |")
    multi = mem.group_by("individual_id").agg(pl.col("population_id")).filter(pl.col("population_id").list.len() > 1)
    lines += ["", f"Individuals assigned to more than one population: {multi.height}."]
    for r in multi.head(30).iter_rows():
        lines.append(f"- {r[0]}: {', '.join(r[1])}")
    assigned = mem["individual_id"].n_unique()
    lines += ["", f"Individuals assigned to at least one population: {assigned} of {ind.height} ({100 * assigned / ind.height:.1f}%). Unassigned individuals are still shown on the map as observations."]
    return "\n".join(lines) + "\n"


def main() -> None:
    ind = pl.read_parquet(PROCESSED / f"aadr_{RELEASE}_individuals.parquet")
    pops, dflt = load_populations()
    mem = assign(ind, pops, dflt)
    mem.write_parquet(PROCESSED / "membership.parquet")
    (REPO / "research" / "notes" / "membership-report.md").write_text(report(ind, mem, pops))
    print(f"memberships: {mem.height}; populations with members: {mem['population_id'].n_unique()}")


if __name__ == "__main__":
    main()
